// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SocialMedia.Models;

public partial class Comment
{
    public int Id { get; set; }

    public int? IdParent { get; set; }

    public string Text { get; set; }

    public int IdPost { get; set; }

    public virtual Comment IdParentNavigation { get; set; }

    public virtual Post IdPostNavigation { get; set; }

    public virtual ICollection<Comment> InverseIdParentNavigation { get; set; } = new List<Comment>();
}