// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SocialMedia.Models;

public partial class DB_SocialContext : DbContext
{
    public DB_SocialContext(DbContextOptions<DB_SocialContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Follow> Follows { get; set; }

    public virtual DbSet<Page> Pages { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Comments_1");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Text)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.IdParentNavigation).WithMany(p => p.InverseIdParentNavigation)
                .HasForeignKey(d => d.IdParent)
                .HasConstraintName("FK_Comments_Comments1");

            entity.HasOne(d => d.IdPostNavigation).WithMany(p => p.Comments)
                .HasForeignKey(d => d.IdPost)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Comments_Posts");
        });

        modelBuilder.Entity<Follow>(entity =>
        {
            entity.ToTable("Follow");

            entity.Property(e => e.id).ValueGeneratedNever();

            entity.HasOne(d => d.FollowingldNavigation).WithMany(p => p.FollowFollowingldNavigations)
                .HasForeignKey(d => d.Followingld)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Follow_Pages1");

            entity.HasOne(d => d.Page).WithMany(p => p.FollowPages)
                .HasForeignKey(d => d.PageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Follow_Pages");
        });

        modelBuilder.Entity<Page>(entity =>
        {
            entity.Property(e => e.id).ValueGeneratedNever();

            entity.HasOne(d => d.User).WithMany(p => p.Pages)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pages_Users");
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK_Comments");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.Caption).HasMaxLength(250);
            entity.Property(e => e.MediaLink)
                .IsRequired()
                .HasMaxLength(150)
                .IsFixedLength();

            entity.HasOne(d => d.Page).WithMany(p => p.Posts)
                .HasForeignKey(d => d.PageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Posts_Pages");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK_User");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.Fullname)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(30)
                .IsFixedLength();
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}