// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SocialMedia.Models;

public partial class Follow
{
    public string Id { get; set; }

    public string PageId { get; set; }

    public string FollowingId { get; set; }

    public virtual Page Following { get; set; }

    public virtual Page Page { get; set; }
}