// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SocialMedia.Models;

public partial class User
{
    public string Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Fullname { get; set; }

    public string email { get; set; }

    public bool Is_Active { get; set; }

    public virtual ICollection<Page> Pages { get; set; } = new List<Page>();
}