// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Components.Web;
using System;
using System.Collections.Generic;

namespace SocialMedia.Models;

public partial class User
{
    public string Id
    {
        get
        {

        }
        set
        {

        }
    }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Fullname { get; set; }

    public string email { get; set; }

    private bool _is_Active;
    public bool Is_Active
    {
        get
        {
            return _is_Active;
        }
        set
        {
            _is_Active = true;
        }
    }

    public virtual ICollection<Page> Pages { get; set; } = new List<Page>();
}